$(document).ready(function(){
    $("#mapTo").click(function(){
	  	if(String($(this).val())=="Arrivo"){
	  		$(this).val("");
	  	    }
	  	});
    $("#mapFrom").click(function(){
	  	if(String($(this).val())=="Partenza"){
	  		$(this).val("");
	  	    }
	  	});  
});